ERRAPP.LS      Robot Name ROBOT 08-JUN-25 13:44     

1" 08-JUN-25 13:41 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
2" 27-MAY-25 18:41 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
3" 27-MAY-25 14:38 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
