ERRAPP.LS      Robot Name ROBOT 17-JUL-25 20:56     

1" 17-JUL-25 20:52 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
2" 17-JUL-25 20:26 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
3" 02-JUL-25 17:54 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
4" 08-JUN-25 13:41 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
5" 27-MAY-25 18:41 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
6" 27-MAY-25 14:38 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
